#worker_processes auto;
#pid /run/nginx.pid;
#error_log /var/log/nginx/error.log;
#include /etc/nginx/modules-enabled/*.conf;

# /etc/nginx/nginx.conf

events {
    worker_connections 1024;
}


server {
    listen 80;
    listen 443 ssl http2;
    server_name 5655.ru;

    # Пути к сертификатам
    ssl_certificate /etc/ssl/certs/5655.crt;      # Публичный сертификат
    ssl_certificate_key /etc/ssl/private/5655.key; # Приватный ключ

    # Для проверки цепочки сертификатов (если есть)
    # ssl_trusted_certificate /etc/ssl/certs/ca-chain.crt;

    # Логи для отладки
    access_log /var/log/nginx/test-access.log;
    error_log /var/log/nginx/test-error.log;

    # Простой эндпоинт для проверки
    location / {
        return 200 "1Hello world\n";
        add_header Content-Type text/plain;
    }
}

